### ISSUE TITLE
Auto Godzamok not rebuying buildings properly

### ISSUE THREAD

**Issue by deadthings** [erbkaiser/FrozenCookies#121] opened 2023-02-27 03:26 UTC
Auto Godzamok has recently stopped working. It will only sell Mines and Factories once, which are never rebought. This is admittedly a guess, but I believe it is because I am using the No Buildings blacklist, which is useful for super late-game grinding. This combination (Auto Godzamok + No Building blacklist mode) worked fine up until a few days ago.

![image](https://user-images.githubusercontent.com/33961641/221465889-e79319f7-e560-4dc6-9423-88b02ae11515.png)

**Comment by erbkaiser** [comment] 2023-02-27 13:19
It's not the blacklist directly, but a problem in Auto-Godz.

I have noticed that Auto-Godzamok fails to rebuy buildings myself, which means that it would be left over to the normal buy mode, which in your case is disabled by the blacklist.

I am trying to find the cause, but no luck so far. I hope I can find it soon, once the Godzamok-rebuy is back operational it should also work with the blocklist again.

**Comment by mg-pl** [comment] 2023-02-27 14:48
I'm not using Godzamok but seems like last update borked other things too.
First I noticed wrinklers were not popped and all my wizard towers were sold, then I realized the whole app looks like peg down by some infinite loop somewhere, slow responding, can barely click anything and... not doing anything. Basically nothing works for me now.
When ascending it buys few cursors and then stops like described again.

**Comment by erbkaiser** [comment] 2023-02-27 14:54
@mg-pl please write down your current FC settings, then use the **Recommended** at the bottom of the options window. This will reset FC, after which hopefully it will work and you can set your desired options again.

**Comment by mg-pl** [comment] 2023-02-27 15:21
Seems like i had AutoBuy off, not sure how that happened.
Anyway, now it's doing something but the (web)app remained hardly responsive.

**Comment by erbkaiser** [comment] 2023-02-27 15:28
Most combos (temporarily) turn off AutoBuy. If anything goes wrong there, it breaks. I have tried to put in some catches on reloading, but it does not always work.

**Comment by erbkaiser** [comment] 2023-03-13 14:48
Should be fixed.

**Closed as completed by erbkaiser** 2023-03-13 14:48 UTC
Labels: bug

**Comment by deadthings** [comment] 2023-03-13 15:06
Excellent - working again! Thanks!
