### ISSUE TITLE
Bug: Sugar Lump Autoharvest settings can break FrozenCookies

### ISSUE THREAD

**Issue by Hringingy** [erbkaiser/FrozenCookies#96] opened 2022-09-08 17:53 UTC
I don't know if it has to do with Dragon's Curve aura swapping, the Auto Rigidel Failsafe, or some interaction between the two, but when I set aura swapping to Dragon's Curve + Reality Bending and turn on auto Rigidel at the same time. When the sugar Lump is ready to harvest, FC will set the auras and Rigidel and just stop working (autobuy stops, GCs don't get clicked, spells don't cast, infobox stops ticking, etc). 

I have auto Dragon auras set to Supreme Intellect/Reality Bending and Godz/Moka/Muri with auto Cyclius turned off in the auto Pantheon

**Comment by erbkaiser** [comment] 2022-09-08 19:03
Like I mentioned before, do not manually swap auras if you are using the automated system.

**Comment by Hringingy** [comment] 2022-09-08 20:20
This time it occurred during an attempted SL auto harvest when I left the game running overnight, not when I manually switched auras. I woke up in the morning to find FC no longer working, just like with the manual swap. Only this time it happened without my intervention. I had to restart the game to get everything working again

**Comment by erbkaiser** [comment] 2022-09-09 08:04
I think I might have seen that happen myself a few times, but I am not sure if it's not being caused by power save/sleep mode timeout. The last time I saw it happen everything was still enabled in the FC settings but indeed it stopped doing its thing.

Everything in FC runs on a timer, if for some reason the Javascript engine stops processing it, there's unfortunately nothing I can do about it. The only way to fix it is to reload, so maybe I should add a force save and reload of the entire game after harvesting a lump -- which just so happens to be every 22-24 hours? But that might break other mods which are not set to automatically start...
I'll think about this some more.

**Comment by Hringingy** [comment] 2022-09-09 10:34
I don't use sleep mode timeout in the game's settings, so I don't think it's that. Maybe it has something to do with the SL timer being changed to past its' falling time? The autoswap seems to not happen until a lot later than it should.

**Comment by erbkaiser** [comment] 2022-09-09 11:45
It can't be something in FC. Nothing can disable the timer and the sugar lump harvest simply checks if the current time is greater than the time needed for the lump to be ripe. Nothing gets disabled.

The sleep timeout I mean is the one in the Javascript engine of the browser itself, not related to the Cookie Clicker setting. Even on Steam, it runs inside a Chromium process.

**Comment by Hringingy** [comment] 2022-09-09 15:58
So the SL auto harvest doesn't check if swapping auras/Rigidel would change the time needed to ripen the SL? Adjusting based on that might fix things. Maybe. Possibly. Idk.

**Comment by erbkaiser** [comment] 2022-09-09 16:02
Yes, it does. The mod continually checks if the lump ripening time is within one hour of now, and then sluts in Rigidel. There is no need to check for other aura effects at that point since if anything else pushes the time limit to below the hour, it will work, and own't otherwise.

Regardless of whether or not Auto-Rigi is enabled or not, the same code that handles lump harvesting handles swapping the auras (if that option is active). There is nothing that stops anything else from working.

This bug is likely not caused by the mod at all.

**Comment by Hringingy** [comment] 2022-09-09 17:09
going on a bit of a tangent, but why does it not try to do the aura swap and Rigidel within ~two hours(I'm not sure of the exact amount, but I know it's 18h 57m 26s since the previous harvest) of ripening time when both aura swap and auto-Rigi are active?

**Comment by erbkaiser** [comment] 2022-09-09 20:21
> why does it not try to do the aura swap and Rigidel within ~two hours(I'm not sure of the exact amount, but I know it's 18h 57m 26s since the previous harvest) of ripening time when both aura swap and auto-Rigi are active?

Because that's a bitch to calculate. The effect is 5% faster growth, not a fixed time decrease like Rigidel has. And there are multiple upgrades that affect sugar lump ripening time including how many grandmas you have.

The relevant code to calculate if a lump should be harvested is more or less this:
if (Date.now() - started >= ripeAge): harvest, where Date.now() is the current Unix time (an integer), started is the stored time for when the lump began growing in Unix time, and ripeAge calls the in-game function to see if a lump is 'ripe', according to all upgrades then active.

For auto-Rigidel, the same calculation is done with the added check of it is 60 minutes or less to the next ripeAge, to allow for the Rigidel swap to harvest one hour earlier.

Applying this same check to the Dragon's Curve aura is certainly possible, but that means doing one of these two things:
1) calculating whatever the total time to ripe is and decreasing it by 5% _every time the check is run_ or
2) adding in a hard-coded list of all possible ripe age decreases for every upgrade

1 is slow in Javascript and would make FC even more sluggish at times, and 2 is an immense pain to code and keep updated. I have no plans to do either for such a small gain.

**Comment by Hringingy** [comment] 2022-09-09 20:54
you can't do a quick n' dirty solution of manually calculating the minimum amount of time saved by Dragon's curve by itself (I assume this could be done by just adding everything other than auras up and then calculating time saved based on that), using that as a fixed value, and then just adding ~56 minutes to that if auto Rigidel is also on at the same time? it might not save an optimum amount of time when you don't have all upgrades but it'll at least save _some_ amount of extra time. Rigidel won't save exactly 1 hour either when Dragon's Curve or more is active, particularly if I have those auras on by default rather than using autoswap as that's what I did before requesting this feature.

**Comment by erbkaiser** [comment] 2022-09-09 21:05
It's just too much of a hassle to calculate so it works for all situations.
If you do happen to run DC anyway, that will be taken into account for the ripeAge calculation. I run with Reality Bending as an aura currently so my ripe age is 10% of 5% shorter, or 18h 46m 21s total.

As this is straying past the bug report as is, I'm closing it and opening a feature request. No guarantees I'll work on it but of course if someone else feels like it, submit a pull request.

**Closed as completed by erbkaiser** 2022-09-09 21:05 UTC
Labels: bug

**Comment by Hringingy** [comment] 2022-09-09 21:11
I was kinda hoping the bug would somehow get fixed if this feature got updated, but I'm not the expert in programming. Thanks for listening to my rant anyway.

**Comment by erbkaiser** [comment] 2022-09-14 20:41
I think I found the actual cause of this bug and it should be fixed now. Auto-Rigidel was expecting a variable that I did not define, so it would kill the entire script instead of harvesting the lump and continuing as usual.

**Comment by Hringingy** [comment] 2022-09-15 10:53
I guess I should mention that I don't think Rigidel's Bonus is always exactly 1 hour in all cases. The Dragon Auras might be changing the 1 hour value since they're multiplicative rather than additive, and that could potentially cause the swap to be mistimed. Possibly.

**Comment by erbkaiser** [comment] 2022-09-15 11:01
The new code should take care of that, it won't allow harvesting if Rigidel misfires. Before it can harvest, the times are recalculated twice: before swapping in Rigi and after. If the lump is not ripe, it will cancel out. That will allow for the normal harvest to kick in, instead. The worst error case still possible is that Rigidel remains in the diamond slot, which should be taken care of by the auto Pantheon function.

**Comment by Hringingy** [comment] 2022-09-20 00:50
it seems that Rigidel can still botch harvests.

I had auto pantheon turned off, manually slotted Godz/Moka/empty
Dragon Auras and Auto Dragon's Curve also off, manually set Curve+RB

when the 1-hour mark hit, Rigidel was slotted and there was a botched harvest
